Sous Chefs Adoption
sous-chefs/yum-amazon pull request #9
Opened 2021-03-08 20:19 UTC by TheREK3R

# Description

- Formally adopt cookbook into sous-chefs
- Add/fix tests

## Issues Resolved

Adds inspec tests. Removes old amazonlinux 1 platform

## Check List

- [X] All tests pass. See TESTING.md for details.
- [X] New functionality includes testing.
- [X] New functionality has been documented in the README if applicable.

2021-03-08 22:01 UTC, ramereth requested changes
It looks like you removed support for version 2 and below. You should mention that in the ChangeLog and we should do a major bump when we release this.

2021-03-08 22:01 UTC, ramereth commented on metadata.rb
> +issues_url        'https://github.com/sous-chefs/yum-centos/issues'
```suggestion
source_url        'https://github.com/sous-chefs/yum-amazon'
issues_url        'https://github.com/sous-chefs/yum-amazon/issues'
```

2021-03-09 00:08 UTC, TheREK3R commented on metadata.rb
> +issues_url        'https://github.com/sous-chefs/yum-centos/issues'
oops

2021-03-09 16:41 UTC, ramereth approved these changes

2021-03-09 16:41 UTC, merged

2021-03-09 16:41 UTC, kitchen-porter commented
Released as: [4.0.0](https://github.com/sous-chefs/yum-amazon/releases/tag/4.0.0)